[theme]
base = "dark"
font="Noto Sans Arabic"
codeFont="Noto Sans Arabic"
baseFontSize=32

[server]
enableStaticServing = true

[[theme.fontFaces]]
family="Noto Sans Arabic"
url="NotoSansArabic-Regular.ttf"
style="normal"
weight=400
